M48
; DRILL file {KiCad 8.0.8} date 2026-01-29T15:06:08+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-29T15:06:08+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X-71.12Y0.0
X0.0Y-76.2
T2
X0.0Y0.0
M30
